name: Teat_CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13'
    - run: npm install
    - run: npm run typecheck
    - run: npm run build
    - run: npm run test
